### ISSUE TITLE
Tetra Pickaxes not dropping portal gate item

### ISSUE THREAD

**Issue by BahkaSheep** [northwesttrees-gaming/PortalGates#16] opened 2023-03-08 12:08 UTC
### Issue description

Breaking the portal gate with a Tetra pickaxe causes it to not drop any item even if the tool is diamond or netherite level 

### Steps to reproduce this issue.

Break gate with diamond pick - behaves as expected
Convert said pick to Tetra pickaxe 
Trying to break the portal gate now results in no item being dropped 

### Minecraft and nod builds

Minecraft version: 1.19.2
Mod version: PortalGates_1.6.2_for_1.19.2
Forge version: 43.2.4

btw you typed nod builds instead of mod builds :^) 

### Installed modifications

PortalGates_1.6.2_for_1.19.2.jar
mutil-1.19.2-5.1.0.jar
tetra-1.19.2-5.0.2.jar

**Comment by northwesttreesgaming** [comment] 2023-03-11 23:05
I just checked the code, portal gate blocks will drop it's self when broken, so whatever is causing the issue is not on Portal Gate's end it's on Tetra's end with whatever they used in the script for their pickaxe. I don't think there is any way I can even add support as I don't know what they did to make it do that so maybe bring it up with them, chances are they won't fix it because this is an MCreator mod but there is really nothing I can do on my end either way.

**Closed as completed by northwesttreesgaming** 2023-03-11 23:05 UTC
Labels: Bug, Wont Fix
